# Generated by Django 5.0.7 on 2024-09-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='firstName')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
    ]
