# Generated by Django 5.0.7 on 2024-08-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_event_submission_delete_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='event',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='participant',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
