# Generated by Django 5.0.7 on 2024-09-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('trans_id', models.CharField(max_length=50, unique=True)),
                ('trans_time', models.DateTimeField()),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_shortcode', models.CharField(max_length=20)),
                ('bill_ref_number', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('third_party_trans_id', models.CharField(blank=True, max_length=100, null=True)),
                ('msisdn', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
