# Generated by Django 5.0.7 on 2024-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_date_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticketLink',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
